## Imprimir Elementos do Array

**Problema**: Considere este array 1X1:

```
arr_1d = [53, 78, 90, 12, 15, 65, 44, 32, 29, 36]
```

1. Imprima o 3º e o 9º elemento do array.
2. Altere o 3º e o 9º elemento para 100.


In [ ]:
# escreva o código aqui

import numpy as np

arr_1d = np.array([53, 78, 90, 12, 15, 65, 44, 32, 29, 36])

print(arr_1d[2])
print(arr_1d[8])

arr_1d[2]=100
arr_1d[8]=100

print(arr_1d)

90
29
[ 53  78 100  12  15  65  44  32 100  36]


## Atualize os Elementos Diagonais do Array Multidimensional

**Problema**: Considerando este array 3x3, altere todos os elementos diagonais da matriz para 0.

```

arr_2d = [[1,2,3],
          [4,5,6],
          [7,8,9]]
```





In [ ]:
#Escreva o código aqui

arr_2d=np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

rows=3
cols=3

for i in range(rows):
  for j in range(cols):
    if i==j:
      arr_2d[i][j]=0
    else:
      pass

print(arr_2d)

[[0 2 3]
 [4 0 6]
 [7 8 0]]


## Números de Linhas e Colunas

**Problema**: Escreva um programa para encontrar o número de linhas e colunas presentes na matriz abaixo. 
Observação: Inicialize a matriz usando NumPy.

```
 A= [[9,5,6,1,-2],
    [3,-8,1,2,0],
    [6,9,3,3,5]]
```



In [ ]:
# escreva o código aqui
import numpy as np

A= np.array([[9,5,6,1,-2],
            [3,-8,1,2,0],
            [6,9,3,3,5]])

#Comprimento de A = número de linhas
cols=len(A[0])

#Comprimento do primeiro array = número de colunas
rows=len(A)
print('número de linhas = ',rows)
print('número de colunas = ',cols)


número de linhas =  3
número de colunas =  5


## Multiplicação Escalar

**Problema**: Imprima cada elemento da matriz a seguir. Inicialize a matriz usando NumPy.  <br />
Além disso, multiplique a matriz por n = 150 e imprima a matriz após a multiplicação.
   
```
 B=[[-8,0,2,4],[5,2,-1,7]]
```


   

In [ ]:
# escreva o código aqui
import numpy as np
B=np.array([[-8,0,2,4],
           [5,2,-1,7]])

rows=len(B)
cols=len(B[0])

n=rows*cols         #número total de elementos

C=np.zeros([rows,cols])

#imprima todos os elementos da matriz
count=1
for i in range (rows):
  for j in range (cols):
      C[i][j]=150*B[i][j]
      if count<=n:
        print('O elemento ',count,' é ', B[i][j])
        count+=1

print('\n', C)

O elemento  1  é  -8
O elemento  2  é  0
O elemento  3  é  2
O elemento  4  é  4
O elemento  5  é  5
O elemento  6  é  2
O elemento  7  é  -1
O elemento  8  é  7

 [[-1200.     0.   300.   600.]
 [  750.   300.  -150.  1050.]]
